<?php

$categoriaController = new CategoriaController();
$pizza = new Pizza();
$pizzaController = new PizzaController();
$helper = new Helper();
$resultado = "";

//deletando o pizza
$del = filter_input(INPUT_GET, "del", FILTER_SANITIZE_NUMBER_INT);
if ($del):
    $pizza = $pizzaController->retornaPizzaImagem($del);
    echo $capa = "../upload/" . $pizza->getThumb();
    if (file_exists($capa) && !is_dir($capa)):
        unlink($capa);
    endif;
    if ($pizzaController->Excluir($del)):
        $resultado = "<div class=\"alert alert-success\">A pizza </b> foi removida com sucesso</div>";
    else:
        $resultado = "<div class=\"alert alert-danger\">Erro ao remover </div>";
    endif;
endif;

//-------------------- INICIANDO PAGINATION TOPO --------------------------
if (empty($_GET['pg'])):
else:
    $pg = $_GET['pg'];
endif;
if (isset($pg)):
    $pg = $_GET['pg'];
else:
    $pg = 1;
endif;
//máximo de links na paginação
$maxlinks = 4;
//quantidade de publicação por páginas
$maximo = 5;
//$inicio = (($maximo * $pagina) - $maximo);
$inicio = ($pg * $maximo) - $maximo;
$listarPizza = $pizzaController->ListarPizza($inicio, $maximo);
?>

<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Receitas Cadastradas</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Listagem de Pizza</h4>                           
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <thead>
                                <th>ID</th>
                                <th>Capa</th>
                                <th>Titulo</th>              
                                <th>Categoria</th>                
                                <th>url</th>
                                <th>Valor</th>
                                <th>Status</th>                            
                                <th>Ações</th>                                               
                                </thead>
                                <tbody>
                                    <?php
                                    if ($listarPizza == null):

                                        echo '<td colspan="8">Nesse momento não temos pizzas cadastrado</td>';                                  
                                    else:
                                        foreach ($listarPizza as $pz):                                         
                                            ?>

                                            <tr>

                                                <td><?= $pz->getCod_pizza(); ?></td>
                                                <td> <img src="../upload/<?= $pz->getThumb(); ?>" width="100" alt=""/></td>
                                                <td><?= $pz->getTitulo(); ?></td>                                       
                                                <td><?= $pz->getCategoria()->getTitulo(); ?></td>                                       
                                                <td><?= $pz->getUrl(); ?></td>
                                                <td><?= $pz->getValor(); ?></td>
                                                <td>
                                                    <?=
                                                    ($pz->getStatus() == 1) ?
                                                            '<btn class="btn btn-fill btn-success btn-icon">'
                                                            . '<i class="fa ti-check"></i>'
                                                            . '</btn></td>' :
                                                            '<btn class="btn btn-fill btn-danger btn-icon">'
                                                            . '<i class="fa fa-times"></i>'
                                                            . '</btn></td>'                                                        
                                                    ?>
                                                </td>


                                                <td>
                                                    <a href="?pagina=editarPizza&cod_pizza=<?= $pz->getCod_pizza(); ?>" class="btn btn-icon btn-primary"><i class="ti-pencil-alt2"></i></a>
                                                    <a href="?pagina=listarPizza&del=<?= $pz->getCod_pizza(); ?>" class="btn btn-icon btn-danger" onclick="return confirm('Deseja realmente excluir a <?= $pz->getTitulo(); ?>');"><i class="ti-close"></i></a>
                                                </td>                                   
                                            </tr>

                                            <?php
                                        endforeach;
                                    endif;
                                    ?>
                                </tbody>
                            </table>

                        </div>
                    </div>
                    <nav aria-label="Page navigation">
                        <?php
                        //paginação de resultados
                        $total = $pizzaController->RetornaQtdPizza();
                        
                        $total_paginas = ceil($total / $maximo);
                        if ($total > $maximo):
                            echo '<div class="paginator">';
                            echo '<ul class="pagination">';
                            echo '<li><a href="dashboard.php?pagina=listarPizza&pg=1">Primeira Página</a></li>';
                            for ($i = $pg - $maxlinks; $i <= $pg - 1; $i++):
                                if ($i >= 1):
                                    echo '<li><a href="dashboard.php?pagina=listarPizza&pg=' . $i . '">' . $i . '</a><li>';
                                endif;
                            endfor;
                            echo '<li><a class="active" href="dashboard.php?pagina=listarPizza&pg=' . $pg . '">' . $pg . '</a></li>';
                            for ($i = $pg + 1; $i <= $pg + $maxlinks; $i++):
                                if ($i <= $total_paginas):
                                    echo '<li><a href="dashboard.php?pagina=listarPizza&pg=' . $i . '">' . $i . '</a></li>';
                                endif;
                            endfor;
                            echo '<li><a href="dashboard.php?pagina=listarPizza&pg=' . $total_paginas . '"">Última Página</a></li>';
                            echo '</ul>';
                            echo '</div>';
                        endif;
                        ?> 

                    </nav>
                </div>

            </div>
        </div>
    </div>
</div>